// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package orders

import (
	"snapshot/internal/types"
)

type OrdersID string

type Orders struct {
	EstimatedDelivery *int64  `json:"estimatedDelivery,omitempty"`
	Id                string  `json:"id"`
	Status            string  `json:"status"`
	TotalPrice        float64 `json:"totalPrice"`
}

type OrdersList struct {
	CreatedAt  string  `json:"createdAt"`
	Id         string  `json:"id"`
	ItemCount  int32   `json:"itemCount"`
	Status     string  `json:"status"`
	TotalPrice float64 `json:"totalPrice"`
}

type OrdersGet struct {
	CreatedAt       string            `json:"createdAt"`
	Id              string            `json:"id"`
	Items           []OrdersItemsItem `json:"items"`
	ShippingAddress types.Address     `json:"shippingAddress"`
	Status          string            `json:"status"`
	TotalPrice      float64           `json:"totalPrice"`
	UpdatedAt       *string           `json:"updatedAt,omitempty"`
}

type OrdersAdminListAllOrders struct {
	Id         string  `json:"id"`
	Status     string  `json:"status"`
	TotalPrice float64 `json:"totalPrice"`
	UserId     string  `json:"userId"`
}

type OrdersItemsItem struct {
	ProductId   string  `json:"productId"`
	ProductName string  `json:"productName"`
	Quantity    int32   `json:"quantity"`
	UnitPrice   float64 `json:"unitPrice"`
}
