// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package orders

import (
	"snapshot/internal/types"
)

type AdminListAllOrdersOrdersRequest struct {
	Page     *int32 `json:"page,omitempty" form:"page"`
	PageSize *int32 `json:"pageSize,omitempty" form:"pageSize"`
}

type AdminListAllOrdersOrdersResponse struct {
	Result  []AdminListAllOrdersOrdersResponseResultItem `json:"result"`
	Success bool                                         `json:"success"`
}

type AdminListAllOrdersOrdersResponseResultItem struct {
	Id         string  `json:"id"`
	Status     string  `json:"status"`
	TotalPrice float64 `json:"totalPrice"`
	UserId     string  `json:"userId"`
}

type CancelOrdersRequest struct {
	Id     string  `json:"id" form:"id" validate:"required"`
	Reason *string `json:"reason,omitempty" form:"reason"`
}

type CancelOrdersResponse struct {
	Data   CancelOrdersResponseData `json:"data"`
	Status bool                     `json:"status"`
}

type CancelOrdersResponseData struct{}

type CreateOrdersRequest struct {
	CouponCode      *string       `json:"couponCode,omitempty" form:"couponCode"`
	Notes           *string       `json:"notes,omitempty" form:"notes" validate:"max=500"`
	ProductId       string        `json:"productId" form:"productId" validate:"required"`
	Quantity        int32         `json:"quantity" form:"quantity" validate:"required"`
	ShippingAddress types.Address `json:"shippingAddress" form:"shippingAddress" validate:"required"`
}

type CreateOrdersResponse struct {
	Result  CreateOrdersResponseResult `json:"result"`
	Success bool                       `json:"success"`
}

type CreateOrdersResponseResult struct {
	EstimatedDelivery *int64  `json:"estimatedDelivery,omitempty"`
	Id                string  `json:"id"`
	Status            string  `json:"status"`
	TotalPrice        float64 `json:"totalPrice"`
}

type GetOrdersRequest struct {
	Id string `json:"id" form:"id" validate:"required"`
}

type GetOrdersResponse struct {
	Result  GetOrdersResponseResult `json:"result"`
	Success bool                    `json:"success"`
}

type GetOrdersResponseResultItemsItem struct {
	ProductId   string  `json:"productId"`
	ProductName string  `json:"productName"`
	Quantity    int32   `json:"quantity"`
	UnitPrice   float64 `json:"unitPrice"`
}

type GetOrdersResponseResult struct {
	CreatedAt       string                             `json:"createdAt"`
	Id              string                             `json:"id"`
	Items           []GetOrdersResponseResultItemsItem `json:"items"`
	ShippingAddress types.Address                      `json:"shippingAddress"`
	Status          string                             `json:"status"`
	TotalPrice      float64                            `json:"totalPrice"`
	UpdatedAt       *string                            `json:"updatedAt,omitempty"`
}

type ListOrdersRequest struct {
	Page     *int32  `json:"page,omitempty" form:"page"`
	PageSize *int32  `json:"pageSize,omitempty" form:"pageSize"`
	Status   *string `json:"status,omitempty" form:"status"`
}

type ListOrdersResponse struct {
	Result  []ListOrdersResponseResultItem `json:"result"`
	Success bool                           `json:"success"`
}

type ListOrdersResponseResultItem struct {
	CreatedAt  string  `json:"createdAt"`
	Id         string  `json:"id"`
	ItemCount  int32   `json:"itemCount"`
	Status     string  `json:"status"`
	TotalPrice float64 `json:"totalPrice"`
}

type TrackOrderOrdersMessage struct {
	OrderId string `json:"orderId" form:"orderId" validate:"required"`
}

type TrackOrderOrdersEvent struct {
	Status    string `json:"status" form:"status" validate:"required"`
	UpdatedAt string `json:"updatedAt" form:"updatedAt" validate:"required"`
}
