// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package orders

import (
	"context"
	service "snapshot/internal/service"
)

type AdminListAllOrdersUsecase interface {
	Execute(ctx context.Context, input AdminListAllOrdersOrdersRequest) (AdminListAllOrdersOrdersResponse, error)
}

type CancelUsecase interface {
	Execute(ctx context.Context, input CancelOrdersRequest) (CancelOrdersResponse, error)
}

type CreateUsecase interface {
	Execute(ctx context.Context, entity Orders) (CreateOrdersResponse, error)
}

type GetUsecase interface {
	Execute(ctx context.Context, id OrdersID) (GetOrdersResponse, error)
}

type ListUsecase interface {
	Execute(ctx context.Context, input ListOrdersRequest) (ListOrdersResponse, error)
}

type adminListAllOrdersUsecaseImpl struct {
	repo     OrdersRepository
	redisSvc service.RedisService
}

type cancelUsecaseImpl struct {
	repo     OrdersRepository
	redisSvc service.RedisService
}

type createUsecaseImpl struct {
	repo     OrdersRepository
	redisSvc service.RedisService
}

type getUsecaseImpl struct {
	repo     OrdersRepository
	redisSvc service.RedisService
}

type listUsecaseImpl struct {
	repo     OrdersRepository
	redisSvc service.RedisService
}

func NewAdminListAllOrdersUsecase(repo OrdersRepository, redisSvc service.RedisService) *adminListAllOrdersUsecaseImpl {
	return &adminListAllOrdersUsecaseImpl{
		repo:     repo,
		redisSvc: redisSvc,
	}
}

func (uc *adminListAllOrdersUsecaseImpl) Execute(ctx context.Context, input AdminListAllOrdersOrdersRequest) (AdminListAllOrdersOrdersResponse, error) {
	// TODO: implement AdminListAllOrdersUsecase
	return AdminListAllOrdersOrdersResponse{}, nil
}

func NewCancelUsecase(repo OrdersRepository, redisSvc service.RedisService) *cancelUsecaseImpl {
	return &cancelUsecaseImpl{
		repo:     repo,
		redisSvc: redisSvc,
	}
}

func (uc *cancelUsecaseImpl) Execute(ctx context.Context, input CancelOrdersRequest) (CancelOrdersResponse, error) {
	// TODO: implement CancelUsecase
	return CancelOrdersResponse{}, nil
}

func NewCreateUsecase(repo OrdersRepository, redisSvc service.RedisService) *createUsecaseImpl {
	return &createUsecaseImpl{
		repo:     repo,
		redisSvc: redisSvc,
	}
}

func (uc *createUsecaseImpl) Execute(ctx context.Context, entity Orders) (CreateOrdersResponse, error) {
	created, err := uc.repo.Create(ctx, entity)
	if err != nil {
		return CreateOrdersResponse{}, err
	}
	// @gen:start ed69ff53
	// TODO: map created to CreateOrdersResponse
	_ = created
	var resp CreateOrdersResponse
	// @gen:end ed69ff53
	return resp, nil
}

func NewGetUsecase(repo OrdersRepository, redisSvc service.RedisService) *getUsecaseImpl {
	return &getUsecaseImpl{
		repo:     repo,
		redisSvc: redisSvc,
	}
}

func (uc *getUsecaseImpl) Execute(ctx context.Context, id OrdersID) (GetOrdersResponse, error) {
	result, err := uc.repo.FindByID(ctx, id)
	if err != nil {
		return GetOrdersResponse{}, err
	}
	// @gen:start d4b7abc4
	// TODO: map result to GetOrdersResponse
	_ = result
	var resp GetOrdersResponse
	// @gen:end d4b7abc4
	return resp, nil
}

func NewListUsecase(repo OrdersRepository, redisSvc service.RedisService) *listUsecaseImpl {
	return &listUsecaseImpl{
		repo:     repo,
		redisSvc: redisSvc,
	}
}

func (uc *listUsecaseImpl) Execute(ctx context.Context, input ListOrdersRequest) (ListOrdersResponse, error) {
	// TODO: implement ListUsecase
	return ListOrdersResponse{}, nil
}
