// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package middleware

import (
	"github.com/gin-gonic/gin"
)

func JwtAuth(c *gin.Context) {
	// TODO: implement JwtAuth
	c.Next()
}
