// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package auth

type AuthRepository interface {
	// Add developer-owned persistence methods outside generated regions as needed.
}

type authRepositoryImpl struct{}

func NewAuthRepository() *authRepositoryImpl {
	return &authRepositoryImpl{}
}
