// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package auth

import (
	"context"
)

type StreamAuthEventsUsecase interface {
	Execute(ctx context.Context, events chan<- StreamAuthEventsAuthEvent, marshal func(StreamAuthEventsAuthEvent) ([]byte, error)) error
}
