// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package products

import (
	"errors"
	"net/http"
	"snapshot/internal/httperr"

	"github.com/gin-gonic/gin"
)

type ProductsHandler struct {
	CreateUsecase CreateUsecase
	ListUsecase   ListUsecase
	GetUsecase    GetUsecase
	UpdateUsecase UpdateUsecase
	RemoveUsecase RemoveUsecase
}

func (h *ProductsHandler) Create(c *gin.Context) {
	var binding CreateProductsRequest
	if err := c.ShouldBindJSON(&binding); err != nil {
		status, body := httperr.ResolveBindingError(err)
		c.JSON(status, body)
		return
	}
	// @gen:start f5ea9736
	// TODO: construct Products entity from binding
	entity := Products{}
	// @gen:end f5ea9736
	output, err := h.CreateUsecase.Execute(c.Request.Context(), entity)
	if err != nil {
		var httpErr httperr.HTTPError
		if errors.As(err, &httpErr) {
			c.JSON(httpErr.HTTPStatus(), err)
		} else {
			c.JSON(http.StatusInternalServerError, gin.H{
				"error": err.Error(),
			})
		}
		return
	}
	c.JSON(http.StatusOK, output)
}

func (h *ProductsHandler) Get(c *gin.Context) {
	id := ProductsID(c.Param("id"))
	output, err := h.GetUsecase.Execute(c.Request.Context(), id)
	if err != nil {
		var httpErr httperr.HTTPError
		if errors.As(err, &httpErr) {
			c.JSON(httpErr.HTTPStatus(), err)
		} else {
			c.JSON(http.StatusInternalServerError, gin.H{
				"error": err.Error(),
			})
		}
		return
	}
	c.JSON(http.StatusOK, output)
}

func (h *ProductsHandler) List(c *gin.Context) {
	var input ListProductsRequest
	if err := c.ShouldBindQuery(&input); err != nil {
		status, body := httperr.ResolveBindingError(err)
		c.JSON(status, body)
		return
	}
	output, err := h.ListUsecase.Execute(c.Request.Context(), input)
	if err != nil {
		var httpErr httperr.HTTPError
		if errors.As(err, &httpErr) {
			c.JSON(httpErr.HTTPStatus(), err)
		} else {
			c.JSON(http.StatusInternalServerError, gin.H{
				"error": err.Error(),
			})
		}
		return
	}
	c.JSON(http.StatusOK, output)
}

func (h *ProductsHandler) Remove(c *gin.Context) {
	var input RemoveProductsRequest
	if err := c.ShouldBindQuery(&input); err != nil {
		status, body := httperr.ResolveBindingError(err)
		c.JSON(status, body)
		return
	}
	input.Id = c.Param("id")
	id := ProductsID(c.Param("id"))
	output, err := h.RemoveUsecase.Execute(c.Request.Context(), id)
	if err != nil {
		var httpErr httperr.HTTPError
		if errors.As(err, &httpErr) {
			c.Status(httpErr.HTTPStatus())
		} else {
			c.Status(http.StatusInternalServerError)
		}
		return
	}
	_ = output
	c.Status(http.StatusNoContent)
}

func (h *ProductsHandler) Update(c *gin.Context) {
	var binding UpdateProductsRequest
	if err := c.ShouldBindJSON(&binding); err != nil {
		status, body := httperr.ResolveBindingError(err)
		c.JSON(status, body)
		return
	}
	id := ProductsID(c.Param("id"))
	// @gen:start 250be001
	// TODO: construct Products entity from binding
	entity := Products{}
	// @gen:end 250be001
	output, err := h.UpdateUsecase.Execute(c.Request.Context(), id, entity)
	if err != nil {
		var httpErr httperr.HTTPError
		if errors.As(err, &httpErr) {
			c.JSON(httpErr.HTTPStatus(), err)
		} else {
			c.JSON(http.StatusInternalServerError, gin.H{
				"error": err.Error(),
			})
		}
		return
	}
	c.JSON(http.StatusOK, output)
}
