// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package service

type RedisService interface {
	Close() error
}

type redisServiceImpl struct {
}

func NewRedisService() (*redisServiceImpl, error) {
	return &redisServiceImpl{}, nil
}

func (s *redisServiceImpl) Close() error {
	return nil
}
