// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package config

import (
	"log"
	"os"
	"strings"

	"github.com/joho/godotenv"
)

type Config struct {
	// Server listen port
	PORT string
}

func Load() Config {
	if err := godotenv.Load(); err != nil {
		log.Println(".env file not loaded, using system env vars:", err)
	}
	var cfg Config

	cfg.PORT = os.Getenv("PORT")
	if cfg.PORT == "" {
		cfg.PORT = "8080"
	}
	if !strings.HasPrefix(cfg.PORT, ":") {
		cfg.PORT = ":" + cfg.PORT
	}
	return cfg
}
