// Code generated by schemago. DO NOT EDIT.
// To modify, change backend.config.ts or wrap changes in @gen:start / @gen:end markers.

package types

type Address struct {
	City    string  `json:"city"`
	Country *string `json:"country,omitempty"`
	Street  string  `json:"street"`
	ZipCode string  `json:"zipCode"`
}
